/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FocusModeEnum, MediaStreamState, MeteringModeEnum, Point2D, VideoFacingModeEnum, VideoResizeModeEnum } from "./components/user-media/user-media";
export namespace Components {
    interface UserMedia {
        /**
          * Applies constraints to a specific track https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/applyConstraints
         */
        "applyConstraints": (constraints: MediaTrackConstraints, type?: 'audio' | 'video', trackIndex?: number) => Promise<void>;
        /**
          * The exact aspect ratio (width in pixels divided by height in pixels, represented as a double rounded to the tenth decimal place) or aspect ratio range.
         */
        "aspectRatio": number;
        /**
          * Simple boolean constraint that will use default stream values if none others are specified. Must be set to `true` to enable the audio track.
         */
        "audio": boolean;
        /**
          * ID for selecting a specific audio device
         */
        "audioDeviceId": string;
        /**
          * Automatically adjusts the volume of the input from the mic
         */
        "autoGainControl": boolean;
        /**
          * Video element attribute
         */
        "autoplay": boolean;
        /**
          * Brightness is "the attribute of a visual sensation according to which an area appears to emit more or less light" and in the context of the present API, it refers to the numeric camera setting that adjusts the perceived amount of light emitting from the photo object. A higher brightness setting increases the intensity of darker areas in a scene while compressing the intensity of brighter parts of the scene.
         */
        "brightness": number;
        /**
          * Number of channels to use with 1 being mono, 2 being stereo
         */
        "channelCount": number;
        /**
          * This range reflects the supported correlated color temperatures to be used for the scene white balance calculation:  incandescent	2500-3500 fluorescent	4000-5000 warm-fluorescent	5000-5500 daylight	5500-6500 cloudy-daylight	6500-8000 twilight	8000-9000 shade	9000-10000
         */
        "colorTemperature": number;
        /**
          * Contrast is the numeric camera setting that controls the difference in brightness between light and dark areas in a scene. A higher contrast setting reflects an expansion in the difference in brightness.
         */
        "contrast": number;
        /**
          * Video element attribute
         */
        "controls": boolean;
        /**
          * Creates a MediaStreamConstraints object based on component attributes
         */
        "createConstraints": () => Promise<MediaStreamConstraints>;
        /**
          * Echo cancellation to prevent feedback between the mic and speakers
         */
        "echoCancellation": boolean;
        /**
          * Exposure Compensation is a numeric camera setting that adjusts the exposure level from the current value used by the implementation. This value can be used to bias the exposure level enabled by auto-exposure, and usually is a symmetric range around 0 EV (the no-compensation value). This value is only used in single-shot and continuous exposureMode.
         */
        "exposureCompensation": number;
        /**
          * Exposure is the amount of light that is allowed to fall on the photosensitive device. In auto-exposure modes (single-shot or continuous exposureMode), the exposure time and/or camera aperture are automatically adjusted by the implementation based on the subject of the photo. In manual exposureMode, these parameters are set to fixed absolute values.
         */
        "exposureMode": MeteringModeEnum;
        /**
          * Exposure Time is a numeric camera setting that controls the length of time during which light is allowed to fall on the photosensitive device. This value is used in manual exposureMode to control exposure. The value is in 100 microsecond units. That is, a value of 1.0 means an exposure time of 1/10000th of a second and a value of 10000.0 means an exposure time of 1 second.
         */
        "exposureTime": number;
        /**
          * Focus distance is a numeric camera setting that controls the focus distance of the lens. The setting usually represents distance in meters to the optimal focus distance.
         */
        "focusDistance": number;
        /**
          * Focus mode describes the focus setting of the capture device (e.g. auto or manual).
         */
        "focusMode": FocusModeEnum;
        /**
          * Refresh rate of the video in frames per second
         */
        "frameRate": number;
        /**
          * Get an object of key/booleans that detail supported track capabilities https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getCapabilities
         */
        "getCapabilities": (type?: 'audio' | 'video', trackIndex?: number) => Promise<MediaTrackCapabilities>;
        /**
          * Gets constraints of a specific track https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getConstraints
         */
        "getConstraints": (type?: 'audio' | 'video', trackIndex?: number) => Promise<void>;
        /**
          * Get a list of available media devices, filtered by kind
         */
        "getMediaDevices": (kind: MediaDeviceKind) => Promise<MediaDeviceInfo[]>;
        /**
          * Get a list of supported constraints https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#specifications
         */
        "getSupportedConstraints": () => Promise<MediaTrackSupportedConstraints>;
        /**
          * Returns the actual track settings after constraints are applied https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getSettings
         */
        "getTrackSettings": (type?: 'audio' | 'video', trackIndex?: number) => Promise<MediaTrackSettings>;
        /**
          * Get the video element used to show the stream
         */
        "getVideoElement": () => Promise<HTMLVideoElement>;
        /**
          * Requested height of video track
         */
        "height": number;
        /**
          * The ISO setting of a camera describes the sensitivity of the camera to light. It is a numeric value, where the lower the value the greater the sensitivity.
         */
        "iso": number;
        /**
          * controls the time between the start of the sound processing and the data being made available to the next step, specified in seconds
         */
        "latency": number;
        /**
          * Video element attribute
         */
        "muted": boolean;
        /**
          * Removes the background noise from the audio signal
         */
        "noiseSuppression": boolean;
        /**
          * Pan is a numeric camera setting that controls the pan of the camera. The setting represents pan in arc seconds, which are 1/3600th of a degree. Values are in the range from -180*3600 arc seconds to +180*3600 arc seconds. Positive values pan the camera clockwise as viewed from above, and negative values pan the camera counter clockwise as viewed from above.
         */
        "pan": number;
        /**
          * Video element attribute
         */
        "playsinline": boolean;
        /**
          * Points of interest describe the metering area centers used in other settings, e.g. exposure, white balance mode and focus mode each one being a Point2D (usually these three controls are modified simultaneously by the so-called 3A algorithm: auto-focus, auto-exposure, auto-white-balance).
         */
        "pointsOfInterest": Array<Point2D>;
        /**
          * Determines if the UA is allowed to use cropping and downscaling on the camera output
         */
        "resizeMode": VideoResizeModeEnum;
        /**
          * Specifies a desired sample rate, higher is better (Audio CDs for example have 44000 samples/s or 44kHz)
         */
        "sampleRate": number;
        /**
          * The linear sample size in bits. This constraint can only be satisfied for audio devices that produce linear samples
         */
        "sampleSize": number;
        /**
          * Saturation is "the colourfulness of an area judged in proportion to its brightness" and in the current context it refers to a numeric camera setting that controls the intensity of color in a scene (i.e. the amount of gray in the scene). Very low saturation levels will result in photos closer to black-and-white.
         */
        "saturation": number;
        /**
          * Sharpness is a numeric camera setting that controls the intensity of edges in a scene. Higher sharpness settings result in higher contrast along the edges, while lower settings result in less contrast and blurrier edges (i.e. soft focus).
         */
        "sharpness": number;
        /**
          * Stops the current stream (all tracks)
         */
        "stopStream": () => Promise<void>;
        /**
          * Reference to current stream, mainly for debugging
         */
        "stream": MediaStream;
        /**
          * Reflected attribute for styling based on stream state
         */
        "streamState": MediaStreamState;
        /**
          * Tilt is a numeric camera setting that controls the tilt of the camera. The setting represents tilt in arc seconds, which are 1/3600th of a degree. Values are in the range from -180*3600 arc seconds to +180*3600 arc seconds. Positive values tilt the camera upward when viewed from the front, and negative values tilt the camera downward as viewed from the front.
         */
        "tilt": number;
        /**
          * Turns on the devices fill light
         */
        "torch": boolean;
        /**
          * Simple boolean constraint that will use default stream values if none others are specified. Must be set to `true` to enable the video track.
         */
        "video": boolean;
        /**
          * ID for selecting a specific video device
         */
        "videoDeviceId": string;
        /**
          * Video track constraint for facing mode
         */
        "videoFacingMode": VideoFacingModeEnum;
        /**
          * Read the docs! Calling this method opens a new browser window and loads the component API documentation.
         */
        "viewDocumentation": () => Promise<void>;
        /**
          * Video element attribute
         */
        "volume": number;
        /**
          * White balance mode is a setting that cameras use to adjust for different color temperatures. Color temperature is the temperature of background light (usually measured in Kelvin).
         */
        "whiteBalanceMode": MeteringModeEnum;
        /**
          * Requested width of video track
         */
        "width": number;
        /**
          * Zoom is a numeric camera setting that controls the focal length of the lens. The setting usually represents a ratio, e.g. 4 is a zoom ratio of 4:1. The minimum value is usually 1, to represent a 1:1 ratio (i.e. no zoom).
         */
        "zoom": number;
    }
}
export interface UserMediaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUserMediaElement;
}
declare global {
    interface HTMLUserMediaElement extends Components.UserMedia, HTMLStencilElement {
    }
    var HTMLUserMediaElement: {
        prototype: HTMLUserMediaElement;
        new (): HTMLUserMediaElement;
    };
    interface HTMLElementTagNameMap {
        "user-media": HTMLUserMediaElement;
    }
}
declare namespace LocalJSX {
    interface UserMedia {
        /**
          * The exact aspect ratio (width in pixels divided by height in pixels, represented as a double rounded to the tenth decimal place) or aspect ratio range.
         */
        "aspectRatio"?: number;
        /**
          * Simple boolean constraint that will use default stream values if none others are specified. Must be set to `true` to enable the audio track.
         */
        "audio"?: boolean;
        /**
          * ID for selecting a specific audio device
         */
        "audioDeviceId"?: string;
        /**
          * Automatically adjusts the volume of the input from the mic
         */
        "autoGainControl"?: boolean;
        /**
          * Video element attribute
         */
        "autoplay"?: boolean;
        /**
          * Brightness is "the attribute of a visual sensation according to which an area appears to emit more or less light" and in the context of the present API, it refers to the numeric camera setting that adjusts the perceived amount of light emitting from the photo object. A higher brightness setting increases the intensity of darker areas in a scene while compressing the intensity of brighter parts of the scene.
         */
        "brightness"?: number;
        /**
          * Number of channels to use with 1 being mono, 2 being stereo
         */
        "channelCount"?: number;
        /**
          * This range reflects the supported correlated color temperatures to be used for the scene white balance calculation:  incandescent	2500-3500 fluorescent	4000-5000 warm-fluorescent	5000-5500 daylight	5500-6500 cloudy-daylight	6500-8000 twilight	8000-9000 shade	9000-10000
         */
        "colorTemperature"?: number;
        /**
          * Contrast is the numeric camera setting that controls the difference in brightness between light and dark areas in a scene. A higher contrast setting reflects an expansion in the difference in brightness.
         */
        "contrast"?: number;
        /**
          * Video element attribute
         */
        "controls"?: boolean;
        /**
          * Echo cancellation to prevent feedback between the mic and speakers
         */
        "echoCancellation"?: boolean;
        /**
          * Exposure Compensation is a numeric camera setting that adjusts the exposure level from the current value used by the implementation. This value can be used to bias the exposure level enabled by auto-exposure, and usually is a symmetric range around 0 EV (the no-compensation value). This value is only used in single-shot and continuous exposureMode.
         */
        "exposureCompensation"?: number;
        /**
          * Exposure is the amount of light that is allowed to fall on the photosensitive device. In auto-exposure modes (single-shot or continuous exposureMode), the exposure time and/or camera aperture are automatically adjusted by the implementation based on the subject of the photo. In manual exposureMode, these parameters are set to fixed absolute values.
         */
        "exposureMode"?: MeteringModeEnum;
        /**
          * Exposure Time is a numeric camera setting that controls the length of time during which light is allowed to fall on the photosensitive device. This value is used in manual exposureMode to control exposure. The value is in 100 microsecond units. That is, a value of 1.0 means an exposure time of 1/10000th of a second and a value of 10000.0 means an exposure time of 1 second.
         */
        "exposureTime"?: number;
        /**
          * Focus distance is a numeric camera setting that controls the focus distance of the lens. The setting usually represents distance in meters to the optimal focus distance.
         */
        "focusDistance"?: number;
        /**
          * Focus mode describes the focus setting of the capture device (e.g. auto or manual).
         */
        "focusMode"?: FocusModeEnum;
        /**
          * Refresh rate of the video in frames per second
         */
        "frameRate"?: number;
        /**
          * Requested height of video track
         */
        "height"?: number;
        /**
          * The ISO setting of a camera describes the sensitivity of the camera to light. It is a numeric value, where the lower the value the greater the sensitivity.
         */
        "iso"?: number;
        /**
          * controls the time between the start of the sound processing and the data being made available to the next step, specified in seconds
         */
        "latency"?: number;
        /**
          * Video element attribute
         */
        "muted"?: boolean;
        /**
          * Removes the background noise from the audio signal
         */
        "noiseSuppression"?: boolean;
        /**
          * Emitted when video frame is updated
         */
        "onFrameupdate"?: (event: UserMediaCustomEvent<any>) => void;
        /**
          * Emitted when stream becomes active
         */
        "onStreamactive"?: (event: UserMediaCustomEvent<any>) => void;
        /**
          * Emitted when stream becomes inactive
         */
        "onStreaminactive"?: (event: UserMediaCustomEvent<any>) => void;
        /**
          * Emitted when stream fails to initialize
         */
        "onStreaminiterror"?: (event: UserMediaCustomEvent<any>) => void;
        /**
          * Pan is a numeric camera setting that controls the pan of the camera. The setting represents pan in arc seconds, which are 1/3600th of a degree. Values are in the range from -180*3600 arc seconds to +180*3600 arc seconds. Positive values pan the camera clockwise as viewed from above, and negative values pan the camera counter clockwise as viewed from above.
         */
        "pan"?: number;
        /**
          * Video element attribute
         */
        "playsinline"?: boolean;
        /**
          * Points of interest describe the metering area centers used in other settings, e.g. exposure, white balance mode and focus mode each one being a Point2D (usually these three controls are modified simultaneously by the so-called 3A algorithm: auto-focus, auto-exposure, auto-white-balance).
         */
        "pointsOfInterest"?: Array<Point2D>;
        /**
          * Determines if the UA is allowed to use cropping and downscaling on the camera output
         */
        "resizeMode"?: VideoResizeModeEnum;
        /**
          * Specifies a desired sample rate, higher is better (Audio CDs for example have 44000 samples/s or 44kHz)
         */
        "sampleRate"?: number;
        /**
          * The linear sample size in bits. This constraint can only be satisfied for audio devices that produce linear samples
         */
        "sampleSize"?: number;
        /**
          * Saturation is "the colourfulness of an area judged in proportion to its brightness" and in the current context it refers to a numeric camera setting that controls the intensity of color in a scene (i.e. the amount of gray in the scene). Very low saturation levels will result in photos closer to black-and-white.
         */
        "saturation"?: number;
        /**
          * Sharpness is a numeric camera setting that controls the intensity of edges in a scene. Higher sharpness settings result in higher contrast along the edges, while lower settings result in less contrast and blurrier edges (i.e. soft focus).
         */
        "sharpness"?: number;
        /**
          * Reference to current stream, mainly for debugging
         */
        "stream"?: MediaStream;
        /**
          * Reflected attribute for styling based on stream state
         */
        "streamState"?: MediaStreamState;
        /**
          * Tilt is a numeric camera setting that controls the tilt of the camera. The setting represents tilt in arc seconds, which are 1/3600th of a degree. Values are in the range from -180*3600 arc seconds to +180*3600 arc seconds. Positive values tilt the camera upward when viewed from the front, and negative values tilt the camera downward as viewed from the front.
         */
        "tilt"?: number;
        /**
          * Turns on the devices fill light
         */
        "torch"?: boolean;
        /**
          * Simple boolean constraint that will use default stream values if none others are specified. Must be set to `true` to enable the video track.
         */
        "video"?: boolean;
        /**
          * ID for selecting a specific video device
         */
        "videoDeviceId"?: string;
        /**
          * Video track constraint for facing mode
         */
        "videoFacingMode"?: VideoFacingModeEnum;
        /**
          * Video element attribute
         */
        "volume"?: number;
        /**
          * White balance mode is a setting that cameras use to adjust for different color temperatures. Color temperature is the temperature of background light (usually measured in Kelvin).
         */
        "whiteBalanceMode"?: MeteringModeEnum;
        /**
          * Requested width of video track
         */
        "width"?: number;
        /**
          * Zoom is a numeric camera setting that controls the focal length of the lens. The setting usually represents a ratio, e.g. 4 is a zoom ratio of 4:1. The minimum value is usually 1, to represent a 1:1 ratio (i.e. no zoom).
         */
        "zoom"?: number;
    }
    interface IntrinsicElements {
        "user-media": UserMedia;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "user-media": LocalJSX.UserMedia & JSXBase.HTMLAttributes<HTMLUserMediaElement>;
        }
    }
}
